word_list = ['understanding', 'great', 'playful', 'calm', 'loving', 'concerned', 'eager',
'irritated', 'lousy', 'upset', 'incapable', 'insensitive', 'fearful', 'crushed', 'tearful', 
'courageous', 'peaceful', 'considerate', 'affected', 'keen', 'enraged', 
'disappointed', 'alone', 'dull', 'terrified', 'tormented', 'sorrowful', 'reliable', 
'joyous', 'energetic', 'ease', 'affectionate', 'fascinated', 'earnest',
'discouraged', 'uncertain', 'paralyzed', 'nonchalant', 'deprived', 
'liberated', 'comfortable', 'sensitive', 'intrigued', 'intent', 
'ashamed', 'indecisive', 'fatigued', 'neutral', 'pained', 
'grief', 'optimistic', 'tender', 'absorbed', 'anxious', 
'rebellious', 'sore', 'powerless', 'perplexed', 'useless', 'reserved', 'alarmed', 'tortured', 
'anguish', 'free', 'delighted', 'provocative', 'encouraged', 'devoted', 'inquisitive',
'annoyed', 'diminished', 'embarrassed', 'inferior', 'weary', 'panic', 'dejected', 'desolate', 'sympathetic', 
'overjoyed', 'impulsive', 'determined', 'guilty', 
'vulnerable', 'bored', 'nervous', 'rejected', 'desperate', 'interested', 'gleeful',
'passionate', 'tenacious', 'hateful', 'dissatisfied', 'shy', 'empty', 'preoccupied', 
'scared', 'injured', 'thankful', 'frisky', 'content', 'admiration', 'engrossed', 
'enthusiastic', 'miserable', 'stupefied', 'forced', 'cold', 'worried', 'unhappy', 
'receptive', 'important', 'animated', 'quiet', 'warm', 'curious', 'detestable', 
'disillusioned', 'hesitant', 'disinterested', 'frightened', 'afflicted', 'lonely', 'accepting', 'festive', 'spirited', 
'certain', 'touched', 'brave', 'bitter', 'repugnant', 'unbelieving', 'despair', 'lifeless', 'timid', 'aching', 'grieved', 
'kind', 'ecstatic', 'thrilled', 'relaxed', 'sympathy', 'daring', 'despicable', 'skeptical', 'frustrated', 
'shaky', 'victimized', 'mournful', 'satisfied', 'wonderful', 'serene', 'close', 'challenged', 'resentful', 'disgusting', 
'distrustful', 'distressed', 'restless', 'heartbroken', 'dismayed', 'loved',
'inflamed', 'abominable', 'misgiving', 'woeful', 'doubtful', 'agonized', 'cheerful', 'comforted', 
'provoked', 'lost', 'pathetic', 'appalled', 'drawn', 'confident', 
'incensed', 'unsure', 'tragic', 'cowardly', 'humiliated', 'merry', 'hopeful', 'infuriated', 
'sulky', 'uneasy', 'wronged', 'elated', 'pessimistic', 
'alienated', 'jubilant', 'worked', 'sense', 'loss', 'tense', 'wary', 'boiling', 'fuming', 'indignant']